from mitmproxy import ctx, http
import json
import os
import re

# Allowlist of permitted domains
# Wildcards are supported: "*.github.com" matches "api.github.com"
ALLOWED_DOMAINS = [
    # Claude / Anthropic
    "api.anthropic.com",

    # GitHub
    "github.com",
    "*.github.com",
    "raw.githubusercontent.com",

    # Python / uv / PyPI
    "pypi.org",
    "files.pythonhosted.org",

    # Node.js / npm
    "registry.npmjs.org",

    # VS Code / Remote Development
    "update.code.visualstudio.com",
    "*.vscode-cdn.net",
    "vscode.download.prss.microsoft.com",
    "az764295.vo.msecnd.net",
    "*.gallerycdn.vsassets.io",
    "marketplace.visualstudio.com",
    "*.vo.msecnd.net",
]

# Passthrough domains bypass TLS interception entirely (for certificate pinning).
# These are set via mitmproxy's ignore_hosts option in the load() hook below,
# replacing the previous --ignore-hosts CLI flag generated by Go code.
PASSTHROUGH_DOMAINS = []


def _parse_domain_entry(entry):
    """Normalize domain entry to dict format with log attribute.

    Supports two formats:
    - String: "api.example.com" -> {"domain": "api.example.com", "log": True}
    - Dict: {"domain": "api.example.com", "log": False} -> returned as-is
    """
    if isinstance(entry, str):
        return {"domain": entry, "log": True}
    return entry


def _get_domain_config(host: str) -> dict | None:
    """Get the domain config entry that matches the given host.

    Returns the parsed domain entry dict if host is allowed, None otherwise.
    Host matching is case-insensitive and ignores a trailing dot.
    """
    host = host.lower().rstrip(".")
    for entry in ALLOWED_DOMAINS:
        config = _parse_domain_entry(entry)
        pattern = config["domain"].lower()
        if pattern.startswith("*."):
            base = pattern[2:]
            if host == base or host.endswith("." + base):
                return config
        elif host == pattern:
            return config
    return None


# Log file path
LOG_FILE_PATH = "/opt/devagent-proxy/logs/requests.jsonl"


# Block GitHub PR merge API calls.
# The @blockGitHubPRMerge flag from the old allowlist.txt format becomes this
# Python boolean. True = block merge API calls, False = allow them.
BLOCK_GITHUB_PR_MERGE = True


def load(loader):
    """Configure mitmproxy options at addon load time."""
    if PASSTHROUGH_DOMAINS:
        # Convert domain patterns to mitmproxy ignore_hosts regex format.
        # mitmproxy matches against "host:port", so the optional (:\d+)? suffix
        # is required or the pattern silently fails to match.
        patterns = []
        for domain in PASSTHROUGH_DOMAINS:
            if domain.startswith("*."):
                pattern = r"^.*\." + re.escape(domain[2:]) + r"(:\d+)?$"
            else:
                pattern = "^" + re.escape(domain) + r"(:\d+)?$"
            patterns.append(pattern)
        ctx.options.ignore_hosts = patterns


def _log_request(flow: http.HTTPFlow) -> None:
    """Log an HTTP request/response to the JSONL file."""
    if flow.response is None:
        return

    duration_ms = 0
    if flow.request.timestamp_start and flow.response.timestamp_end:
        duration_ms = int((flow.response.timestamp_end - flow.request.timestamp_start) * 1000)

    entry = {
        "ts": flow.response.timestamp_end or flow.request.timestamp_start or 0,
        "method": flow.request.method,
        "url": flow.request.url,
        "status": flow.response.status_code,
        "duration_ms": duration_ms,
        "req_headers": dict(flow.request.headers),
        "res_headers": dict(flow.response.headers),
    }

    try:
        log_dir = os.path.dirname(LOG_FILE_PATH)
        if log_dir:
            os.makedirs(log_dir, exist_ok=True)
        with open(LOG_FILE_PATH, "a") as f:
            f.write(json.dumps(entry) + "\n")
    except Exception as e:
        ctx.log.error(f"Failed to write proxy log: {e}")


class AllowlistFilter:
    """Blocks requests to domains not in the allowlist and optionally blocks PR merges."""

    def _is_allowed(self, host: str) -> bool:
        """Check if host matches any allowed domain pattern."""
        return _get_domain_config(host) is not None

    def _is_github_pr_merge(self, flow: http.HTTPFlow) -> bool:
        """Check if request is a GitHub PR merge attempt."""
        if not BLOCK_GITHUB_PR_MERGE:
            return False

        # Match the real connection target, not the spoofable Host header.
        host = flow.request.host.lower()
        if host not in ("api.github.com", "github.com") and not host.endswith(".github.com"):
            return False

        # REST API: PUT /repos/{owner}/{repo}/pulls/{number}/merge
        if flow.request.method == "PUT":
            if re.match(r"^/repos/[^/]+/[^/]+/pulls/\d+/merge$", flow.request.path):
                return True

        # GraphQL API: POST /graphql with mergePullRequest mutation
        if flow.request.method == "POST" and flow.request.path == "/graphql":
            content = flow.request.get_text()
            if content and "mergePullRequest" in content:
                return True

        return False

    def _block(self, flow: http.HTTPFlow, message: str) -> None:
        """Set a 403 response on the flow and log it."""
        flow.response = http.Response.make(
            403, message.encode(), {"Content-Type": "text/plain"}
        )
        _log_request(flow)

    def http_connect(self, flow: http.HTTPFlow) -> None:
        """Enforce the allowlist at TLS-tunnel establishment.

        For HTTPS, the CONNECT authority (flow.request.host) is the real,
        unspoofable destination of the tunnel. Blocking here stops a disallowed
        tunnel before it opens, regardless of any Host header sent inside it.
        """
        try:
            host = flow.request.host
            if not self._is_allowed(host):
                self._block(flow, f"Domain '{host}' is not in the allowlist\n")
        except Exception as e:
            ctx.log.error(f"http_connect filter error, blocking: {e}")
            self._block(flow, "proxy filter error\n")

    def request(self, flow: http.HTTPFlow) -> None:
        # Fail closed: any unexpected error blocks the request rather than
        # letting it through (mitmproxy otherwise forwards on hook exceptions).
        try:
            # Check PR merge block first
            if self._is_github_pr_merge(flow):
                self._block(flow, "Merging pull requests is not allowed in this environment. Do not retry.\n")
                return

            # Authorize on the connection target (flow.request.host), which
            # reflects the absolute-URI authority (plain HTTP) or the CONNECT/SNI
            # target (HTTPS) -- NOT the client-controlled Host header. Also
            # require the Host header itself to be allowlisted, to blunt
            # domain-fronting against shared CDNs present in the allowlist.
            conn_host = flow.request.host
            header_host = flow.request.pretty_host
            if not (self._is_allowed(conn_host) and self._is_allowed(header_host)):
                self._block(flow, f"Domain '{conn_host}' is not in the allowlist\n")
        except Exception as e:
            ctx.log.error(f"request filter error, blocking: {e}")
            self._block(flow, "proxy filter error\n")

    def response(self, flow: http.HTTPFlow) -> None:
        """Log completed HTTP request/response to JSONL file."""
        if flow.response is None:
            return

        # Check if this domain should be logged (keyed off the real target).
        host = flow.request.host
        config = _get_domain_config(host)
        if config is None or not config.get("log", True):
            return

        _log_request(flow)

addons = [AllowlistFilter()]
